import calendar
yy=2023   ## DEBES ELEGIR EL NUMERO DE AÑO QUE QUIERES VISUALIZAR
mm=7      ##DEBES ELEGIR EL NUMERO DE MES QUE QUIERES VISUALIZAR
print(calendar.month(yy,mm))  ##MOSTRAMOS EN TERMINAL EL CALENDARIO DEL MES Y AÑO QUE ELEGIMOS